# Generated by Django 4.1.7 on 2023-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articles_id', models.AutoField(primary_key=True, serialize=False)),
                ('articles_name', models.CharField(blank=True, max_length=100, null=True)),
                ('articles_image', models.FileField(upload_to='media/')),
                ('articles_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_message', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
