# Generated by Django 4.1.7 on 2023-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_image', models.FileField(upload_to='media/')),
                ('city_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('forest_id', models.AutoField(primary_key=True, serialize=False)),
                ('forest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('forest_image', models.FileField(upload_to='media/')),
                ('forest_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('island_id', models.AutoField(primary_key=True, serialize=False)),
                ('island_name', models.CharField(blank=True, max_length=100, null=True)),
                ('island_image', models.FileField(upload_to='media/')),
                ('island_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snow',
            fields=[
                ('snow_id', models.AutoField(primary_key=True, serialize=False)),
                ('snow_name', models.CharField(blank=True, max_length=100, null=True)),
                ('snow_image', models.FileField(upload_to='media/')),
                ('snow_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
