# Generated by Django 4.1.7 on 2023-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0002_city_forest_island_snow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_image', models.FileField(upload_to='media/')),
                ('category_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Forest',
        ),
        migrations.DeleteModel(
            name='Island',
        ),
        migrations.DeleteModel(
            name='Snow',
        ),
    ]
