# Generated by Django 4.1.7 on 2023-03-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0003_category_delete_city_delete_forest_delete_island_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='articles_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamstravel.category'),
        ),
    ]
