# Generated by Django 4.1.7 on 2023-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0004_articles_articles_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='articles_lines',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
