# Generated by Django 4.1.7 on 2023-03-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
