# Generated by Django 4.1.7 on 2023-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
