# Generated by Django 4.1.7 on 2023-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
