# Generated by Django 4.1.7 on 2023-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0013_comments_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_email',
            new_name='comments_email',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_id',
            new_name='comments_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_lines',
            new_name='comments_lines',
        ),
    ]
