# Generated by Django 4.1.7 on 2023-03-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0014_rename_comment_email_comments_comments_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamstravel.articles'),
        ),
    ]
