# Generated by Django 4.1.7 on 2023-03-27 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0015_comments_comments_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
