# Generated by Django 4.1.7 on 2023-03-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0016_comments_comments_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_date_posted',
        ),
    ]
