# Generated by Django 4.1.7 on 2023-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0017_remove_comments_comments_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
