# Generated by Django 4.1.7 on 2023-03-27 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreamstravel', '0018_alter_subscribe_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
